name: CI/CD Projet13

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip setuptools wheel
            python -m pip install -r requirements.txt
            python -m pip install pytest flake8

      - name: Lint - flake8
        run: flake8 src/ sentry/

      - name: Run tests
        run: |
          export PYTHONPATH=$(pwd)/src
          python -m pytest -q
      

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image
        run: |
            USERLC=$(echo "${{ secrets.DOCKER_USERNAME }}" | tr '[:upper:]' '[:lower:]')
            docker build -t ghcr.io/$USERLC/lettings:latest .
        
      - name: Push Docker image to GHCR
        env:
            GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
        run: |
            USERLC=$(echo "${{ secrets.DOCKER_USERNAME }}" | tr '[:upper:]' '[:lower:]')
            echo "$GHCR_TOKEN" | docker login ghcr.io -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
            docker push ghcr.io/$USERLC/lettings:latest
        


            This is a Tier 2 configuration:
            https://docs.brew.sh/Support-Tiers#tier-2
            You can report Tier 2 unrelated issues to Homebrew/* repositories!
            Read the above document before opening any issues or PRs.
          
            ==> make native VERSION=2.0.1
            xcode-select --install
          