name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1Ô∏è‚É£ Checkout Projet13
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2Ô∏è‚É£ Install Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 3Ô∏è‚É£ Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install pytest flake8

      # 4Ô∏è‚É£ Linter
      - name: Lint with flake8
        run: |
          python -m flake8 src/ sentry/

      # 5Ô∏è‚É£ Pytests
      - name: Run tests
        run: |
          export PYTHONPATH=$(pwd)/src
          python -m pytest -q

      # 6Ô∏è‚É£ Clone Django project
      - name: Clone Django project
        run: |
          git clone https://github.com/OpenClassrooms-Student-Center/Python-OC-Lettings-FR.git

      # 7Ô∏è‚É£ Copy Dockerfile inside Django project
      - name: Copy Dockerfile
        run: |
          cp Dockerfile Python-OC-Lettings-FR/

      # 8Ô∏è‚É£ Build Docker image
      - name: Build Docker image
        run: |
          cd Python-OC-Lettings-FR
          docker build -t ghcr.io/${{ secrets.DOCKER_USERNAME,, }}/lettings:latest .


      # 9Ô∏è‚É£ Push Docker image
      - name: Push Docker image to GHCR
        run: |
          echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push ghcr.io/${{ secrets.DOCKER_USERNAME,, }}/lettings:latest


      # üîü Deploy on Oracle VM
      - name: Deploy on Oracle VM
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            docker pull ghcr.io/${{ secrets.DOCKER_USERNAME }}/lettings:latest
            docker stop lettings || true
            docker rm lettings || true
            docker run -d -p 8000:8000 --name lettings ghcr.io/${{ secrets.DOCKER_USERNAME,, }}/lettings:latest

