name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
         python -m pip install --upgrade pip setuptools wheel
         python -m pip install -r requirements.txt || echo "requirements OK"
         python -m pip install pytest==7.4.0 flake8
        
      - name: Debug - Check pytest installation
        run: |
            which python
            python --version
            python -m pip list
            python -m pytest --version
        
      - name: Run tests
        run: |
            export PYTHONPATH=$(pwd)/src
            python -m pytest -q
        
        

      - name: Lint with flake8
        run: |
          python -m flake8 src/ sentry/

      - name: Run tests
        run: |
          export PYTHONPATH=$(pwd)/src
          python -m pytest -q

      - name: Clone Django project
        run: |
          git clone https://github.com/OpenClassrooms-Student-Center/Python-OC-Lettings-FR.git

      - name: Build Docker image
        run: |
          cd Python-OC-Lettings-FR
          USERLC=$(echo "${{ secrets.DOCKER_USERNAME }}" | tr '[:upper:]' '[:lower:]')
          docker build -t ghcr.io/$USERLC/lettings:latest .

      - name: Push Docker image to GHCR
        env:
          GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
        run: |
          USERLC=$(echo "${{ secrets.DOCKER_USERNAME }}" | tr '[:upper:]' '[:lower:]')
          echo "$GHCR_TOKEN" | docker login ghcr.io -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push ghcr.io/$USERLC/lettings:latest

      - name: Deploy on Oracle VM
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            USERLC=$(echo "${{ secrets.DOCKER_USERNAME }}" | tr '[:upper:]' '[:lower:]')
            docker pull ghcr.io/$USERLC/lettings:latest
            docker stop lettings || true
            docker rm lettings || true
            docker run -d -p 8000:8000 --name lettings ghcr.io/$USERLC/lettings:latest
